// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class SelectContext
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject selectContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.SelectContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Label("Label"),
		updateAttribute("updateAttribute"),
		SecondName("SecondName"),
		ImageUrl("ImageUrl"),
		SelectContext_AnimalOwner("MyFirstModule.SelectContext_AnimalOwner");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SelectContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.SelectContext"));
	}

	protected SelectContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject selectContextMendixObject)
	{
		if (selectContextMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.SelectContext", selectContextMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.SelectContext");

		this.selectContextMendixObject = selectContextMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SelectContext.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.SelectContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.SelectContext.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.SelectContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.SelectContext(context, mendixObject);
	}

	public static myfirstmodule.proxies.SelectContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.SelectContext.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Label
	 */
	public final java.lang.String getLabel()
	{
		return getLabel(getContext());
	}

	/**
	 * @param context
	 * @return value of Label
	 */
	public final java.lang.String getLabel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Label.toString());
	}

	/**
	 * Set value of Label
	 * @param label
	 */
	public final void setLabel(java.lang.String label)
	{
		setLabel(getContext(), label);
	}

	/**
	 * Set value of Label
	 * @param context
	 * @param label
	 */
	public final void setLabel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String label)
	{
		getMendixObject().setValue(context, MemberNames.Label.toString(), label);
	}

	/**
	 * @return value of updateAttribute
	 */
	public final java.lang.Integer getupdateAttribute()
	{
		return getupdateAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of updateAttribute
	 */
	public final java.lang.Integer getupdateAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.updateAttribute.toString());
	}

	/**
	 * Set value of updateAttribute
	 * @param updateattribute
	 */
	public final void setupdateAttribute(java.lang.Integer updateattribute)
	{
		setupdateAttribute(getContext(), updateattribute);
	}

	/**
	 * Set value of updateAttribute
	 * @param context
	 * @param updateattribute
	 */
	public final void setupdateAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer updateattribute)
	{
		getMendixObject().setValue(context, MemberNames.updateAttribute.toString(), updateattribute);
	}

	/**
	 * @return value of SecondName
	 */
	public final java.lang.String getSecondName()
	{
		return getSecondName(getContext());
	}

	/**
	 * @param context
	 * @return value of SecondName
	 */
	public final java.lang.String getSecondName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SecondName.toString());
	}

	/**
	 * Set value of SecondName
	 * @param secondname
	 */
	public final void setSecondName(java.lang.String secondname)
	{
		setSecondName(getContext(), secondname);
	}

	/**
	 * Set value of SecondName
	 * @param context
	 * @param secondname
	 */
	public final void setSecondName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String secondname)
	{
		getMendixObject().setValue(context, MemberNames.SecondName.toString(), secondname);
	}

	/**
	 * @return value of ImageUrl
	 */
	public final java.lang.String getImageUrl()
	{
		return getImageUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageUrl
	 */
	public final java.lang.String getImageUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ImageUrl.toString());
	}

	/**
	 * Set value of ImageUrl
	 * @param imageurl
	 */
	public final void setImageUrl(java.lang.String imageurl)
	{
		setImageUrl(getContext(), imageurl);
	}

	/**
	 * Set value of ImageUrl
	 * @param context
	 * @param imageurl
	 */
	public final void setImageUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String imageurl)
	{
		getMendixObject().setValue(context, MemberNames.ImageUrl.toString(), imageurl);
	}

	/**
	 * @return value of SelectContext_AnimalOwner
	 */
	public final myfirstmodule.proxies.AnimalOwner getSelectContext_AnimalOwner() throws com.mendix.core.CoreException
	{
		return getSelectContext_AnimalOwner(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectContext_AnimalOwner
	 */
	public final myfirstmodule.proxies.AnimalOwner getSelectContext_AnimalOwner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.AnimalOwner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SelectContext_AnimalOwner.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.AnimalOwner.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SelectContext_AnimalOwner
	 * @param selectcontext_animalowner
	 */
	public final void setSelectContext_AnimalOwner(myfirstmodule.proxies.AnimalOwner selectcontext_animalowner)
	{
		setSelectContext_AnimalOwner(getContext(), selectcontext_animalowner);
	}

	/**
	 * Set value of SelectContext_AnimalOwner
	 * @param context
	 * @param selectcontext_animalowner
	 */
	public final void setSelectContext_AnimalOwner(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.AnimalOwner selectcontext_animalowner)
	{
		if (selectcontext_animalowner == null)
			getMendixObject().setValue(context, MemberNames.SelectContext_AnimalOwner.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SelectContext_AnimalOwner.toString(), selectcontext_animalowner.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return selectContextMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.SelectContext that = (myfirstmodule.proxies.SelectContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.SelectContext";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
